---
title: "Covid_Cases"
author: "W. Hough"
date: "2022-09-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Import and Inspect Data

Import required packages
```{r, message=FALSE}
library("tidyverse")
library("lubridate")
```


The Covid 19 data is imported from this site:


```{r, message=FALSE}
url <- 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/'
path <- 'csse_covid_19_time_series/'
file_names <- c('time_series_covid19_confirmed_global.csv', 
                'time_series_covid19_deaths_global.csv',
                'time_series_covid19_confirmed_US.csv',
                'time_series_covid19_deaths_US.csv')
urls <- str_c(path, file_names)

global_cases <- read_csv(urls[1])
global_deaths <- read_csv(urls[2])
US_cases <- read_csv(urls[3])
US_deaths <- read_csv(urls[4])
```



```{r, echo=TRUE}
global_cases <- global_cases %>%
  pivot_longer(cols = -c('Province/State',
                         'Country/Region',
                         Lat, Long),
               names_to = "date",
               values_to = "cases") %>%
  select(-c(Lat, Long))

global_deaths <- global_deaths %>%
  pivot_longer(cols = -c('Province/State',
                         'Country/Region',
                         Lat, Long),
               # names_to = "date",
               values_to = "deaths") %>%
  select(-c(Lat, Long))

global <- global_cases %>%
  full_join(global_deaths) %>%
  rename(Country_Region = 'Country/Region',
         Province_State = 'Province/State',) %>%
  mutate(date = mdy(date))
```

```{r}
US_cases <- US_cases %>% 
  pivot_longer(cols = -(UID:Combined_Key),
               names_to = "date",
               values_to = "cases") %>%
  select(Admin2:cases) %>%
  mutate(date = mdy(date)) %>%
  select(-c(Lat, Long_))

US_deaths <- US_deaths %>% 
  pivot_longer(cols = -(UID:Population),
               names_to = "date",
               values_to = "deaths") %>%
  select(Admin2:deaths) %>%
  mutate(date = mdy(date)) %>%
  select(-c(Lat, Long_))

US <- US_cases %>%
    full_join(US_deaths)
```

```{r}
global <- global %>%
   unite("Combined_Key",
         c(Province_State, Country_Region),
         sep = " ,",
         na.rm = TRUE,
         remove = FALSE)

uid_lookup_path <- 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/'
uid_filename <- 'UID_ISO_FIPS_LookUpT_Table.csv'

```

```{r}
uid_filename <- 'UID_ISO_FIPS_LookUp_Table.csv'
uid <- read_csv(uid_filename) %>%
    select(-c(Lat, Long_, Combined_Key, code3, iso2, iso3, Admin2))

global <- global %>%
   left_join(uid, by = c("Province_State", "Country_Region")) %>%
   select(-c(UID, FIPS)) %>%
   select(Province_State, Country_Region, date,
          cases, deaths, Population, Combined_Key)
```

