name: data_mining
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.9.0
  - aiosignal=1.2.0
  - anaconda-catalogs=0.2.0
  - appdirs=1.4.4
  - appnope=0.1.3
  - archspec=0.2.1
  - asttokens=2.4.1
  - attrs=23.1.0
  - backports=1.1
  - backports.functools_lru_cache=1.6.4
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - beautifulsoup4=4.12.2
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.11.17
  - cctools=949.0.1
  - cctools_osx-arm64=949.0.1
  - certifi=2023.11.17
  - cffi=1.16.0
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpickle=2.2.1
  - clyent=1.2.2
  - comm=0.1.4
  - conda-content-trust=0.2.0
  - conda-pack=0.6.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - conda-verify=3.4.2
  - cryptography=41.0.3
  - dask-core=2023.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - filelock=3.13.1
  - fmt=9.1.0
  - frozenlist=1.4.0
  - fsspec=2023.10.0
  - future=0.18.3
  - glob2=0.7
  - icu=73.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - intake=0.6.6
  - ipykernel=6.26.0
  - ipython=8.18.1
  - jedi=0.19.1
  - jinja2=3.1.2
  - jsonpatch=1.32
  - jsonpointer=2.1
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - krb5=1.20.1
  - ld64=530
  - ld64_osx-arm64=530
  - ldid=2.1.5
  - libarchive=3.6.2
  - libcurl=8.4.0
  - libcxx=14.0.6
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libiconv=1.16
  - liblief=0.12.3
  - libllvm14=14.0.6
  - libmamba=1.5.3
  - libmambapy=1.5.3
  - libnghttp2=1.57.0
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libssh2=1.10.0
  - libxml2=2.10.4
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - more-itertools=10.1.0
  - msgpack-python=1.0.3
  - multidict=6.0.4
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - openssl=3.2.0
  - packaging=23.1
  - parso=0.8.3
  - partd=1.4.1
  - patch=2.7.6
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - pkginfo=1.9.6
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - prompt-toolkit=3.0.41
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-lief=0.12.3
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.17.2
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-libarchive-c=2.9
  - python-snappy=0.6.1
  - python.app=3
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - readline=8.2
  - referencing=0.30.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - requests-toolbelt=1.0.0
  - rpds-py=0.10.6
  - ruamel.yaml=0.17.21
  - ruamel_yaml=0.17.21
  - setuptools=68.0.0
  - six=1.16.0
  - snappy=1.1.9
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tapi=1100.0.11
  - tk=8.6.12
  - toolz=0.12.0
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.7.1
  - truststore=0.8.0
  - typing_extensions=4.8.0
  - tzdata=2023c
  - urllib3=1.26.18
  - wcwidth=0.2.12
  - wheel=0.38.4
  - xz=5.4.2
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yarl=1.9.3
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - astunparse==1.6.3
      - cachetools==5.3.2
      - flatbuffers==23.5.26
      - gast==0.5.4
      - google-auth==2.25.1
      - google-auth-oauthlib==1.1.0
      - google-pasta==0.2.0
      - grpcio==1.59.3
      - h5py==3.10.0
      - keras==2.15.0
      - libclang==16.0.6
      - markdown==3.5.1
      - ml-dtypes==0.2.0
      - numpy==1.26.2
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - protobuf==4.23.4
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-macos==2.15.0
      - tensorflow-metal==1.1.0
      - termcolor==2.4.0
      - werkzeug==3.0.1
      - wrapt==1.14.1
